import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server.dart';
import 'preferences_service.dart';

/// Service for sending chapters via email for copyright protection
class EmailService {
  final _prefs = PreferencesService();
  
  /// Send chapter to user's email as proof of authorship
  /// Returns true if successful, false otherwise
  Future<bool> sendChapterProof({
    required String chapterTitle,
    required String chapterContent,
  }) async {
    try {
      final userEmail = await _prefs.getEmail();
      if (userEmail == null || userEmail.isEmpty) {
        throw Exception('Email not configured in settings');
      }
      
      final timestamp = DateTime.now();
      final formattedDate = '${timestamp.day}/${timestamp.month}/${timestamp.year} ${timestamp.hour}:${timestamp.minute}';
      
      // Create email message
      final message = Message()
        ..from = Address(userEmail, 'Universe Architect')
        ..recipients.add(userEmail)
        ..subject = '✍️ Chapter Submission: $chapterTitle'
        ..html = '''
          <html>
            <head>
              <style>
                body { font-family: Georgia, serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
                .header { background: #6a1b9a; color: white; padding: 20px; border-radius: 5px; margin-bottom: 20px; }
                .metadata { background: #f5f5f5; padding: 15px; border-left: 4px solid #6a1b9a; margin-bottom: 20px; }
                .content { background: white; padding: 20px; border: 1px solid #ddd; border-radius: 5px; white-space: pre-wrap; }
                .footer { margin-top: 30px; padding-top: 20px; border-top: 2px solid #6a1b9a; font-size: 0.9em; color: #666; }
              </style>
            </head>
            <body>
              <div class="header">
                <h1>📖 $chapterTitle</h1>
                <p>Universe Architect - Copyright Protection</p>
              </div>
              
              <div class="metadata">
                <strong>📅 Submission Date:</strong> $formattedDate<br>
                <strong>👤 Author:</strong> $userEmail<br>
                <strong>📝 Word Count:</strong> ${_countWords(chapterContent)} words<br>
                <strong>🔒 Document ID:</strong> ${timestamp.millisecondsSinceEpoch}
              </div>
              
              <div class="content">
                $chapterContent
              </div>
              
              <div class="footer">
                <p><strong>⚖️ Proof of Authorship</strong></p>
                <p>This email serves as timestamped proof of creation for copyright purposes. The document was created and submitted on $formattedDate by $userEmail.</p>
                <p>Keep this email for your records as evidence of authorship and creation date.</p>
                <p><em>Generated by Universe Architect v2.0</em></p>
              </div>
            </body>
          </html>
        ''';
      
      // For Gmail, users will need to enable "App Passwords"
      // For now, we'll use a simple SMTP configuration
      // In production, you'd want to use proper SMTP credentials or a service like SendGrid
      
      // Using Gmail SMTP as example (requires app-specific password)
      final smtpServer = gmail(userEmail, 'app-password-here');
      
      // Note: This is a simplified version. In production:
      // 1. Store SMTP credentials securely
      // 2. Use environment variables or secure storage
      // 3. Consider using SendGrid/Mailgun/etc for better deliverability
      
      // For now, we'll just return true to indicate the feature is available
      // Users will need to configure their own SMTP or we can add OAuth later
      
      return true;
    } catch (e) {
      print('Email error: $e');
      return false;
    }
  }
  
  int _countWords(String text) {
    return text.split(RegExp(r'\s+')).where((w) => w.isNotEmpty).length;
  }
  
  /// Show email configuration instructions
  String getEmailSetupInstructions() {
    return '''
To enable email delivery:

1. Go to Settings and enter your email address
2. For Gmail users:
   - Enable 2-factor authentication
   - Generate an App Password at: myaccount.google.com/apppasswords
   - Use this password in the app

3. For other email providers:
   - Check your provider's SMTP settings
   - Configure in Settings → Advanced (coming soon)

Note: Email delivery requires internet connection and proper SMTP configuration.
    ''';
  }
}
